### ISSUE TITLE
Unable to creat printer on OSX

### ISSUE THREAD

**Issue by Nemesis81** [cblt2l/FreeCAD-CuraEngine-Plugin#7]
got this while trying to create a new printer:

`Running the Python command 'createMachineDef' failed:
Traceback (most recent call last):
  File "/Applications/FreeCAD 2.app/Contents/Mod/cura_engine/Commands.py", line 51, in Activated
    panel = MachineDef.PrintBedTaskPanel()
  File "/Applications/FreeCAD 2.app/Contents/Mod/cura_engine/MachineDef.py", line 246, in **init**
    self.form = uic.loadUi(self.homeDir + "/.FreeCAD/Mod/FreeCAD-CuraEngine-Plugin/MachineDef.ui")
  File "<string>", line 4, in <module>

Cannot open file`

maybe just a path problem

**Comment by fcacarminati** [comment]
Just do 

mkdir ~/.FreeCAD
ln -s /Applications/FreeCAD.app/Contents/Mod/ ~/.FreeCAD/

However even with this mod the program will fail later on. First of all the path has to be set to the Cura engine

 /Applications/Cura.app/Contents/MacOS/CuraEngine

but even so something is wrong in the invocation sequence for mac. This package is not yet supported on mac.

**Comment by fcacarminati** [comment]
OK, for whoever is concerned, these are my mods for the mac. 

```
diff FreeCAD-CuraEngine-Plugin/SlicerPanel.py /Applications/FreeCAD.app/Contents/Mod/FreeCAD-CuraEngine-Plugin/SlicerPanel.py
172c172
< 		docDir = FreeCAD.ActiveDocument.FileName.replace(docName + ".fcstd", "")
---
> 		docDir = FreeCAD.ActiveDocument.FileName.replace(docName + ".FCStd", "")
257c257,260
< 		_cmdList.insert(1, "-v")
---
> 		_cmdList.insert(1, "slice")
>                 _cmdList.insert(2, "-v")
>                 _cmdList.insert(3, "-j")
>                 _cmdList.insert(4, "/Applications/Cura.app//Contents/Resources/resources/definitions/101Hero.def.json")
259a263
>                 _cmdList.append("-l")
```

In this way a file is produced, however... note that I had to insert by hand the printer definition, since I could not find a default one.
